name: Notify Parent Repository

on:
  push:
    branches: [main]  # Adjust if your default branch is different
  release:
    types: [published]

jobs:
  notify-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger parent repo update
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PARENT_REPO_TOKEN }}" \
            https://api.github.com/repos/mathiswitte/typst-resume-content/dispatches \
            -d '{"event_type":"template-updated","client_payload":{"ref":"${{ github.ref }}","sha":"${{ github.sha }}"}}'